DROP PROCEDURE IF EXISTS SELECT_SCHOOL_RANK_BY_DATETYPE;
DROP PROCEDURE IF EXISTS SAVE_SCHOOL_RANK;
DROP PROCEDURE IF EXISTS SAVE_USER_RANK;
DROP PROCEDURE IF EXISTS SELECT_USER_RANK_BY_CLASS;
DROP PROCEDURE IF EXISTS SELECT_USER_RANK_BY_SCHOOL;